checkout:
  post:
    - ./.circle_support/checkout_merge_commit.sh

machine:
  services:
    - docker

dependencies:
  override:
    - docker info

test:
  override:
    - docker build -t condaforge/linux-anvil linux-anvil
