version: 2

jobs:
  build:
    working_directory: ~/test
    machine: true
    steps:
      - checkout
      - run:
          name: Merge PRs
          command: ./.circleci/checkout_merge_commit.sh
      - run:
          name: Info about provided Docker
          command: docker info
      - run:
          name: Test building image
          command: ./.circleci/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
